# Generated by Django 3.0.5 on 2020-04-09 13:52

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedocument',
            name='user',
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(null=True, storage=mysite.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
